spring.application.name=date-service
# localhost -> configserver after add Docker-compose
configserver.import = configserver:${CONFIG_SERVER_URL:http://localhost:8888} 
spring.config.import = ${configserver.import}
spring.cloud.config.import-check.enabled = false